### ISSUE TITLE
Make "error" messages colorized by default

### ISSUE THREAD

**Issue by fresonn** [lmittmann/tint#74]
### Am I doing the right thing?

Playground [link](https://goplay.tools/snippet/pgZqTpKE_vK)

I want to make my "error" keys colorized by default with `tint.Err`

The most optimal way I found:
```golang
ReplaceAttr: func(groups []string, a slog.Attr) slog.Attr {

	if a.Key == "error" {
		v, ok := a.Value.Any().(error)
		if !ok {
		  return a
		}
		return tint.Err(v)
	}

	return a
},
```

Then I use it like this:
```golang
var err = errors.New("app error")
slog.Error("app", "error", err)
```

It turns out to be such a beautiful log
<img width="354" alt="image" src="https://github.com/user-attachments/assets/3e4b1b71-0dc0-49d2-af55-2f63e82be26d">

**Comment by lmittmann** [comment]
This has been a popular change request (color all errors red), and your solution is actually really nice, as it achieves exactly it without any code changes. Since v1.0.5 you can modify the tint.Err attribute name, so you could even keep that (instead of always using "err" as a key.

Here is a slightly modified version, that colors all errors red, and even keeps the errors key:
```go
ReplaceAttr: func(groups []string, a slog.Attr) slog.Attr {
	err, ok := a.Value.Any().(error)
	if !ok {
		return a
	}

	key := a.Key
	a = tint.Err(err)
	a.Key = key
	return a
},
```

**Comment by fresonn** [comment]
Could you please update the examples? So that others can know about this feature. It took me 1.5 hours to figure it out 😅

Thanks 🙏
